// export const Virar_to_dhanu_slow_train_route = {
//   train_no:'930017',
//   train_type:"SLOW",
//     stops: [
//     { time: "08:59", name: "VIRAR",          platform: "PF4 LEFT",  major: true,  endpoint: false, highlighted: true },
//     { time: "09:09", name: "VAITARANA",      platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:17", name: "SAPHALE",        platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:23", name: "KELVE ROAD",     platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "09:30", name: "PALGHAR",        platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:36", name: "UMROLI ROAD",    platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:42", name: "BOISAR",         platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "09:50", name: "VANGAON",        platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "10:15", name: "DAHANU ROAD",    platform: "PF4|5",     major: true,  endpoint: true  },
//   ]
// }

// export const Virar_to_dhanu_fast_train_route = {
//      stops: [
//     { time: "08:59", name: "VIRAR",          platform: "PF4 LEFT",  major: true,  endpoint: false, highlighted: true },
//     { time: "09:09", name: "VAITARANA",      platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:17", name: "SAPHALE",        platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:23", name: "KELVE ROAD",     platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "09:30", name: "PALGHAR",        platform: "PF1 LEFT",  major: false, endpoint: false },
//     { time: "09:42", name: "BOISAR",         platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "09:50", name: "VANGAON",        platform: "PF2 RIGHT", major: false, endpoint: false },
//     { time: "10:15", name: "DAHANU ROAD",    platform: "PF4|5",     major: true,  endpoint: true  },
//   ]

// }
/**
 * DRD SERVICES — PTT-78
 * W.E.F 12.10.2024 | UPDATED 01.01.2026
 * DN TRAINS (Down: Towards Dahanu Road)
 *
 * Route codes:
 *   VR-DRD  = Virar → Dahanu Road
 *   CCG-DRD = Churchgate → Dahanu Road
 *   BVI-DRD = Borivali → Dahanu Road
 *   DDR-DRD = Dadar → Dahanu Road
 *
 * Train type is inferred from stops:
 *   FAST trains skip intermediate stations (fewer stops between Churchgate and Virar)
 *   SLOW trains call at all intermediate stations
 *
 * Platform data is not visible in the timetable; fields are left as "" (unknown).
 * "major" = true for bold-printed stations in the original timetable.
 */

// ─── TRAIN 93001 | VR-DRD | SLOW (starts at Virar) ───────────────────────────

export const train_93001 = {
  train_no: "93001",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "04:50",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "05:01",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:09",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:16",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:32",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:38",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:44",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:52",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:15",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93003 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93003 = {
  train_no: "93003",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "05:35",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "05:46",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:54",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:00",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:08",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:15",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:21",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:28",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:50",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93005 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93005 = {
  train_no: "93005",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "05:03",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "05:06",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:08",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:11",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:13",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:20",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:27",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:36",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:49",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:58",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:05",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:15",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:25",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:33",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:40",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:56",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:02",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:08",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:17",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:38",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93007 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93007 = {
  train_no: "93007",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "05:52",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "05:55",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:57",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:00",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:05",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:13",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:18",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:26",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:39",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:47",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:54",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:04",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:14",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:22",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:29",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:44",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:50",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:56",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:04",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:25",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93009 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93009 = {
  train_no: "93009",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "07:11",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "07:14",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:16",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:19",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:22",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:29",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:35",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:45",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:58",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:08",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:18",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:29",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:41",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:49",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:55",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:03",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:10",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:16",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:24",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:50",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93011 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93011 = {
  train_no: "93011",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "07:42",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "07:45",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:47",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:50",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:52",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "07:59",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:04",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:12",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:25",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:39",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:49",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:01",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:10",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:18",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:24",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:32",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:38",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:44",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:52",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:15",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93013 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93013 = {
  train_no: "93013",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "09:30",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "09:41",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:49",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "09:56",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:12",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:18",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:24",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:32",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:50",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93015 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93015 = {
  train_no: "93015",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "08:49",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "08:52",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:54",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:57",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:59",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:06",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:11",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:19",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:32",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:46",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:57",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:07",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:16",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:24",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:31",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:40",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:46",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:52",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:00",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:25",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93017 | BVI-DRD | SLOW (starts at Borivali) ──────────────────────
export const train_93017 = {
  train_no: "93017",
  route: "BVI-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "10:26",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "10:41",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:53",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:05",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:15",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:23",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:29",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:37",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:43",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:51",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "12:00",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:20",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93019 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93019 = {
  train_no: "93019",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "10:03",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "10:06",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:08",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:11",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:13",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:20",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:25",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:33",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:47",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:01",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:13",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:25",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:36",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:44",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:51",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:59",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "12:05",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:11",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "12:19",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:40",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93021 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93021 = {
  train_no: "93021",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "12:00",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "12:11",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:19",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:26",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:40",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "12:46",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:54",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "13:02",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    }, // not visible, estimated
    {
      time: "13:34",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93023 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93023 = {
  train_no: "93023",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "12:20",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "12:30",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:38",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:44",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:06",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "13:12",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:19",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "13:26",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:49",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93025 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93025 = {
  train_no: "93025",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "13:20",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "13:31",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:38",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:44",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:52",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "13:57",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:03",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "14:11",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:26",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93027 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93027 = {
  train_no: "93027",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "15:00",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "15:11",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:19",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:25",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:33",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "15:39",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:46",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:05",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:20",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93029 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93029 = {
  train_no: "93029",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "15:45",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "15:57",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:05",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:11",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:19",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:25",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:32",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:52",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:08",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93031 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93031 = {
  train_no: "93031",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "15:18",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "15:21",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:23",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:26",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:28",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "15:35",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "15:40",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "15:48",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:03",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:12",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:21",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:29",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "16:39",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:47",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "16:55",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:18",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "17:24",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:30",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "17:38",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:00",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93033 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93033 = {
  train_no: "93033",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "18:18",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "18:28",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:35",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:41",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:55",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:01",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:07",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:15",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:30",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93035 | DDR-DRD | SLOW (starts at Dadar) ─────────────────────────
export const train_93035 = {
  train_no: "93035",
  route: "DDR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "18:00",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "18:06",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "18:14",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "18:28",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "18:34",
      name: "DAHISAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:38",
      name: "MIRA ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:43",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "18:49",
      name: "NAIGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:55",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:01",
      name: "NALLASOPARA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:07",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:17",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:25",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:31",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:39",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:45",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:51",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:00",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:20",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93037 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93037 = {
  train_no: "93037",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "20:30",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "20:41",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:49",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:55",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:18",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:24",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:30",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:38",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:55",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_93039 = {
  train_no: "93039",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "21:05",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "21:16",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:24",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:31",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:40",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:46",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:53",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "22:01",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "22:16",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_93041 = {
  train_no: "93041",
  route: "CCG-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "20:20",
      name: "CHURCHGATE",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "20:23",
      name: "MARINE LINES",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:25",
      name: "CHARNI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:28",
      name: "GRANT ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:30",
      name: "MBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:37",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:42",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:51",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:06",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:17",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:29",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:41",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:51",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:59",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "22:06",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "22:20",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "22:26",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "22:33",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "22:48",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:05",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 19101 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_19101 = {
  train_no: "19101",
  route: "VIRAR-BHARUCH EXP",
  train_type: "SLOW",
  cars: 19,
  stops: [
    {
      time: "04:35",
      departure: "04:36",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "04:45",
      departure: "04:46",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "04:53",
      departure: "04:54",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:01",
      departure: "05:02",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:10",
      departure: "05:11",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    // { time: null, name: "UMROLI",      platform: "", major: false, endpoint: false },
    {
      time: "05:21",
      departure: "05:22",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:32",
      departure: "05:33",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:45",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 09051 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_09051 = {
  train_no: "09051",
  route: "DADAR-BHUSAWAL",
  train_type: "FAST",
  cars: "N/A",
  stops: [
    {
      time: "00:05",
      departure: "00:05",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "00:37",
      departure: "00:40",
      name: "BORIVALI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "01:05",
      departure: "01:07",
      name: "VIRAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "01:29",
      departure: "01:31",
      name: "PALGHAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "01:50",
      departure: "01:52",
      name: "BOISAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "01:58",
      name: "DAHANU ROAD",
      platform: "",
      major: false,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 09051 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_00001 = {
  train_no: "00001",
  route: "DAHANU ROAD SPECIAL",
  train_type: "FAST",
  cars: "N/A",
  stops: [
    {
      time: "04:10",
      departure: "04:10",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: null,
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      name: "PALGHAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    { time: null, name: "UMROLI", platform: "", major: false, endpoint: false },
    { time: null, name: "BOISAR", platform: "", major: false, endpoint: false },
    {
      time: null,
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:25",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_69143 = {
  train_no: "69143",
  route: "VR-DRD",
  train_type: "SLOW",
  cars: 12,
  stops: [
    {
      time: "05:15",
      departure: "05:15",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "05:24",
      departure: "05:25",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:32",
      departure: "05:33",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:40",
      departure: "05:41",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "05:48",
      departure: "05:49",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "05:55",
      departure: "05:56",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:01",
      departure: "06:02",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "06:09",
      departure: "06:10",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "06:14",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_69139 = {
  train_no: "69139",
  route: "VR-DRD",
  train_type: "FAST",
  cars: 17,
  stops: [
    {
      time: "07:20",
      departure: "07:20",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "07:29",
      departure: "07:30",
      name: "VASAI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:43",
      departure: "07:45",
      name: "VIRAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "07:54",
      departure: "07:55",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:01",
      departure: "08:02",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:08",
      departure: "08:09",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:19",
      departure: "08:20",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:30",
      departure: "08:32",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "08:44",
      departure: "08:45",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "08:58",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_09055 = {
  train_no: "09055",
  route: "BDTS-UDN SPL",
  train_type: "FAST",
  cars: "N/A",
  stops: [
    {
      time: "09:00",
      departure: "09:00",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "09:08",
      departure: "09:10",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:27",
      departure: "09:29",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:43",
      departure: "09:45",
      name: "BHAYANDAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "09:54",
      departure: "09:56",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:06",
      departure: "10:08",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:17",
      departure: "10:18",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:26",
      departure: "10:27",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:37",
      departure: "10:38",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:50",
      departure: "10:52",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:02",
      departure: "11:04",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:23",
      departure: "11:24",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:40",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_19015 = {
  train_no: "19015",
  route: "DDR-PBR",
  train_type: "FAST",
  cars: 19,
  stops: [
    {
      time: "09:00",
      departure: "09:30",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "09:47",
      departure: "09:50",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:13",
      departure: "10:15",
      name: "VASAI ROAD",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:28",
      departure: "10:30",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:43",
      departure: "10:45",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "10:58",
      departure: "11:00",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:10",
      departure: "11:12",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:28",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_59045 = {
  train_no: "59045",
  route: "MMCT-VAPI",
  train_type: "FAST",
  cars: 21,
  stops: [
    {
      time: "09:55",
      departure: "09:55",
      name: "MUMBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "10:27",
      departure: "10:29",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "10:58",
      departure: "11:00",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:14",
      departure: "11:15",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:33",
      departure: "11:35",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "11:48",
      departure: "11:50",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:08",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_59039 = {
  train_no: "59039",
  route: "VR-BL PASSENGER",
  train_type: "FAST",
  cars: 17,
  stops: [
    {
      time: "11:30",
      departure: "11:30",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "11:37",
      departure: "11:38",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:43",
      departure: "11:44",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:49",
      departure: "11:50",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "11:54",
      departure: "11:55",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:11",
      departure: "12:12",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "12:24",
      departure: "12:25",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "12:33",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_19417 = {
  train_no: "19417",
  route: "MMCT-ADI",
  train_type: "FAST",
  cars: 15,
  stops: [
    {
      time: "13:40",
      departure: "13:40",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "13:48",
      departure: "13:50",
      name: "VASAI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "13:53",
      departure: "13:55",
      name: "VIRAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:04",
      departure: "14:05",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:14",
      departure: "14:15",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:29",
      departure: "14:30",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "14:39",
      departure: "14:40",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "14:49",
      departure: "14:50",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "15:03",
      departure: "15:05",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "15:38",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_19001 = {
  train_no: "19001",
  route: "VIRAR-SURAT EXP",
  train_type: "FAST",
  cars: 21,
  stops: [
    {
      time: "17:00",
      departure: "17:00",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "17:07",
      departure: "17:08",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:13",
      departure: "17:14",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:19",
      departure: "17:20",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:25",
      departure: "17:26",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "17:34",
      departure: "17:35",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "17:43",
      departure: "17:44",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "18:03",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_59023 = {
  train_no: "59023",
  route: "MMCT-VALSAD",
  train_type: "FAST",
  cars: 21,
  stops: [
    {
      time: "18:10",
      departure: "18:10",
      name: "MUMBAI CENTRAL",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "18:18",
      departure: "18:20",
      name: "DADAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "18:40",
      departure: "18:42",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:08",
      departure: "19:10",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:19",
      departure: "19:20",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:29",
      departure: "19:30",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:39",
      departure: "19:40",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "19:47",
      departure: "19:48",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "19:54",
      departure: "19:55",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:19",
      departure: "20:20",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "20:38",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93041 | CCG-DRD | SLOW (starts at Churchgate) ─────────────────────
export const train_22927 = {
  train_no: "22927",
  route: "LOKSHAKTI EXP",
  train_type: "FAST",
  cars: "22",
  stops: [
    {
      time: "19:40",
      departure: "19:40",
      name: "BANDRA",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "19:47",
      departure: "19:50",
      name: "ANDHERI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:09",
      departure: "20:14",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "20:43",
      departure: "20:45",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:03",
      departure: "21:05",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:18",
      departure: "21:20",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:33",
      departure: "21:35",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:53",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

export const train_69161 = {
  train_no: "69161",
  route: "PNVL-DRD MEMU",
  train_type: "SLOW",
  cars: 10,
  stops: [
    {
      time: "21:00",
      departure: "21:00",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "21:09",
      departure: "21:09",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:14",
      departure: "21:15",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:24",
      departure: "21:25",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:30",
      departure: "21:31",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "21:39",
      departure: "21:39",
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "21:49",
      departure: "21:50",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "22:01",
      departure: "22:02",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "22:32",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_69173 = {
  train_no: "69173",
  route: "VIRAR-DAHANU MEMU",
  train_type: "FAST",
  cars: 20,
  stops: [
    {
      time: "22:50",
      departure: "22:50",
      name: "VIRAR",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "22:58",
      departure: "22:59",
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:04",
      departure: "23:05",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:10",
      departure: "23:11",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:19",
      departure: "23:20",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "UMROLI",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:34",
      departure: "23:35",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "23:44",
      departure: "23:45",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "00:15",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

// ─── TRAIN 93039 | VR-DRD | SLOW (starts at Virar) ───────────────────────────
export const train_19425 = {
  train_no: "19425",
  route: "MMCT-NANDURBAR",
  train_type: "FAST",
  cars: 15,
  stops: [
    {
      time: "22:50",
      departure: "22:50",
      name: "BORIVALI",
      platform: "",
      major: true,
      endpoint: false,
      highlighted: true,
    },
    {
      time: "22:58",
      departure: "23:00",
      name: "BHAYANDAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:10",
      departure: "23:12",
      name: "VASAI ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:18",
      departure: "23:20",
      name: "VIRAR",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: null,
      departure: null,
      name: "VAITARANA",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:28",
      departure: "23:30",
      name: "SAPHALE",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "23:40",
      departure: "23:42",
      name: "KELVE ROAD",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "00:03",
      departure: "00:05",
      name: "PALGHAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "00:28",
      departure: "00:30",
      name: "BOISAR",
      platform: "",
      major: true,
      endpoint: false,
    },
    {
      time: "00:38",
      departure: "00:40",
      name: "VANGAON",
      platform: "",
      major: false,
      endpoint: false,
    },
    {
      time: "00:57",
      name: "DAHANU ROAD",
      platform: "",
      major: true,
      endpoint: true,
    },
  ],
};

export const ALL_DN_TRAINS = [
  train_09051,
  train_00001,
  train_19101,
  train_93001,
  train_69143,
  train_93003,
  train_93005,
  train_93007,
  train_69139,
  train_93009,
  train_93011,
  train_93013,
  train_93015,
  train_09055,
  train_19015,
  train_59045,
  train_93017,
  train_93019,
  train_59039,
  train_93021,
  train_93023,
  train_93025,
  train_19417,
  train_93027,
  train_93029,
  train_93031,
  train_19001,
  train_93033,
  train_93035,
  train_59023,
  train_93037,
  train_22927,
  train_69161,
  train_93039,
  train_93041,
  train_69173,
  train_19425,
];

function getTrainTimeFromAll(source, trains) {
  let results = [];

  for (let train of trains) {
    const stop = train.stops.find(s => s.name === source);
    if (stop) {
      results.push({
        train_no: train.train_no,
        route: train.route,
        time: stop.time
      });
    }
  }

  return results.length > 0 ? results : "nothing found";
}

// Example usage:
console.log(getTrainTimeFromAll("VIRAR", ALL_DN_TRAINS));



// console.log(getTrainTime("VIRAR", train_93007));

// console.log(getTrainTime("VIRAR", train_93003));

// console.log(train_93007['stops'][0]['name'],train_93007['stops'][0]['time'])